### ISSUE TITLE
Default loading not show properly the correct color on Dark Mode

### ISSUE THREAD

**Issue by LucazzP** [emanuel-braz/mobx_widget#1]
![image](https://user-images.githubusercontent.com/43015129/81192522-ba301f80-8f90-11ea-8cb5-c2f69becd019.png)

The correct color should be the accent color(do not need to be explicit the color, Flutter does this automatically), as is by default on Flutter

**Comment by emanuel-braz** [comment]
Hi @LucazzP sorry for the delay, I'll gonna fix that.   
Thank you for letting me know.

**Comment by emanuel-braz** [comment]
Closing the issue with PR #3
