### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by subzero911** [emanuel-braz/mobx_widget#2]
Source code uses empty Containers:
![image](https://user-images.githubusercontent.com/12999702/93200248-36651b80-f758-11ea-9496-0f05b4d7637a.png)

Containers are "heavy" widgets, consider replacing it with SizedBox.shrink();

**Comment by emanuel-braz** [comment]
Hi @subzero911 , thanks you for the tip! I'll gonna fix that!

**Comment by subzero911** [comment]
Even better, **const** SizedBox.shrink()

**Comment by emanuel-braz** [comment]
Closing the issue with PR #3 

![Screen Shot 2020-09-23 at 21 51 33](https://user-images.githubusercontent.com/3827308/94088521-0b796800-fde7-11ea-9e76-ef58992d332f.png)
