### ISSUE TITLE
Null Safety Support

### ISSUE THREAD

**Issue by britov** [emanuel-braz/mobx_widget#5]
🏗 Enhancement Proposal
Hello, are there any plans for supporting null safety.

Pitch
As Null Safety is officially out, all packages should migrate to null safety so Apps can too!

**Comment by emanuel-braz** [comment]
@britov 

Thank you for open this issue, I gonna fix that.

**Comment by emanuel-braz** [comment]
Version 0.5.0 fix this. Closing issue with PR #7
