### ISSUE TITLE
no exist my_store.g.dart file.

### ISSUE THREAD

**Issue by sonic0987** [emanuel-braz/mobx_widget#6]
<img width="897" alt="스크린샷 2021-06-09 오전 2 23 13" src="https://user-images.githubusercontent.com/19163775/121230018-ad83a680-c8c9-11eb-86bb-e9eb7e1ed10d.png">

hasn't file my_store.g.dart

**Comment by emanuel-braz** [comment]
Please, run `flutter pub run build_runner build --delete-conflicting-outputs` in order to generate the missing file.
